name: Mirror EasyList

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone EasyList repository
      run: git clone https://github.com/easylist/easylist.git

    - name: Process filter rules
      run: |
        mkdir -p adcrunch_filters
        find easylist -name '*.txt' | while read file; do
          mkdir -p $(dirname adcrunch_filters/$file)
          sed -e 's/\$third-party/\$3p/g' -e 's/~third-party/\1p/g' -e 's/\$xmlhttprequest/\$xhr/g' $file > adcrunch_filters/$file
        done

    - name: Commit and push changes
      run: |
        cd adcrunch_filters
        git init
        git remote add origin git@github.com:AdCrunchSoftware/Filters.git
        git add .
        git commit -m "Mirror EasyList with custom replacements"
        git push -f origin master
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: github-actions@github.com
